<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { PhArrowLeft, PhDownloadSimple, PhFile, PhPencilSimple, PhPhone, PhPlus, PhShieldCheck } from '@phosphor-icons/vue'
import StatusBadge from '../components/StatusBadge.vue'
import { date, money } from '../utils/formatters'
import api from '../services/api'

const route = useRoute(); const borrower = ref(null); const loading = ref(true); const error = ref(''); const tab = ref('overview'); const exporting = ref(false)
const initials = computed(() => borrower.value?.full_name.split(' ').map((item) => item[0]).slice(0, 2).join('').toUpperCase())
const documentLabels = { national_id_front: 'National ID — front', national_id_back: 'National ID — back', borrower_photo: 'Borrower photograph', proof_of_residence: 'Proof of residence', lc1_letter: 'LC1 letter', income_evidence: 'Income evidence', business_evidence: 'Business evidence', bank_statement: 'Bank statement', mobile_money_statement: 'Mobile money statement' }
async function load() { loading.value = true; error.value = ''; try { borrower.value = (await api.get(`/borrowers/${route.params.id}`)).data } catch (e) { error.value = e.response?.status === 404 ? 'Borrower not found.' : 'Borrower profile could not be loaded.' } finally { loading.value = false } }
async function exportCsv() { exporting.value = true; try { const { data } = await api.get(`/borrowers/${route.params.id}/export.csv`, { responseType: 'blob' }); const url = URL.createObjectURL(data); const link = document.createElement('a'); link.href = url; link.download = `borrower-${route.params.id}.csv`; link.click(); URL.revokeObjectURL(url) } catch { error.value = 'The borrower application could not be exported.' } finally { exporting.value = false } }
async function downloadDocument(document) { try { const { data } = await api.get(`/documents/${document.id}/download`, { responseType: 'blob' }); const url = URL.createObjectURL(data); const link = window.document.createElement('a'); link.href = url; link.download = document.original_name; link.click(); URL.revokeObjectURL(url) } catch { error.value = 'The document could not be downloaded.' } }
onMounted(load)
</script>

<template>
  <div class="space-y-5"><RouterLink to="/borrowers" class="back-link"><PhArrowLeft :size="17"/>Borrowers</RouterLink>
    <div v-if="loading" class="skeleton-stack"><i/><i/><i/></div><p v-else-if="error && !borrower" class="form-error">{{ error }} <button class="font-semibold underline" @click="load">Retry</button></p>
    <template v-else>
      <section class="profile-hero"><div class="profile-avatar">{{ initials }}</div><div class="profile-identity"><p class="eyebrow">{{ borrower.borrower_type?.replace('_', ' ') }}</p><h2>{{ borrower.full_name }}</h2><p>{{ borrower.phone_number }} · {{ borrower.district }}</p></div><div class="profile-actions"><a :href="`tel:${borrower.phone_number}`" class="btn-secondary"><PhPhone :size="17"/>Call</a><button class="btn-secondary" :disabled="exporting" @click="exportCsv"><PhDownloadSimple :size="17"/>CSV</button><RouterLink :to="`/borrowers/${borrower.id}/edit`" class="btn-secondary"><PhPencilSimple :size="17"/>Edit</RouterLink><RouterLink :to="{ path: '/loans/new', query: { borrower: borrower.id } }" class="btn-primary"><PhPlus :size="17"/>New loan</RouterLink></div></section>
      <nav class="record-tabs" aria-label="Borrower profile sections"><button v-for="item in ['overview','documents','next of kin','loans']" :key="item" :class="{ active: tab === item }" @click="tab = item">{{ item }}</button></nav>
      <p v-if="error" class="form-error">{{ error }}</p>
      <section v-if="tab === 'overview'" class="detail-grid">
        <article class="premium-panel"><header class="panel-heading"><div><p class="eyebrow">Identity</p><h2>Personal details</h2></div></header><dl class="definition-grid"><div><dt>NIN / ID number</dt><dd>{{ borrower.nin }}</dd></div><div><dt>ID type</dt><dd>{{ borrower.id_type?.replace('_', ' ') }}</dd></div><div><dt>Date of birth</dt><dd>{{ date(borrower.date_of_birth) }}</dd></div><div><dt>Email</dt><dd>{{ borrower.email || '—' }}</dd></div><div><dt>Address</dt><dd>{{ borrower.address }}</dd></div><div><dt>Locality</dt><dd>{{ [borrower.village, borrower.parish, borrower.sub_county, borrower.district].filter(Boolean).join(', ') }}</dd></div></dl></article>
        <article class="premium-panel"><header class="panel-heading"><div><p class="eyebrow">Affordability</p><h2>Work and income</h2></div></header><dl class="definition-grid"><div><dt>Occupation</dt><dd>{{ borrower.occupation }}</dd></div><div><dt>Business / employer</dt><dd>{{ borrower.business_name || borrower.employer_name || '—' }}</dd></div><div><dt>Monthly income</dt><dd>{{ money(borrower.monthly_income) }}</dd></div><div><dt>Monthly expenses</dt><dd>{{ money(borrower.monthly_expenses) }}</dd></div><div><dt>Disposable income</dt><dd>{{ money(borrower.disposable_income) }}</dd></div><div><dt>Repayment source</dt><dd>{{ borrower.repayment_source }}</dd></div></dl></article>
      </section>
      <section v-else-if="tab === 'documents'" class="premium-panel overflow-hidden"><header class="panel-heading"><div><p class="eyebrow">Private evidence</p><h2>Borrower documents</h2></div><span>{{ borrower.documents.length }} files</span></header><div v-if="!borrower.documents.length" class="empty-state"><span><PhFile :size="27"/></span><h2>No documents uploaded</h2><p>Edit this borrower to add identity and affordability evidence.</p></div><div v-else class="document-list p-5"><article v-for="document in borrower.documents" :key="document.id"><div><strong>{{ documentLabels[document.category] || document.category.replaceAll('_', ' ') }}</strong><span>{{ document.original_name }}</span></div><button @click="downloadDocument(document)">Download</button></article></div></section>
      <section v-else-if="tab === 'next of kin'" class="premium-panel"><header class="panel-heading"><div><p class="eyebrow">Emergency contact</p><h2>Next of kin</h2></div><PhShieldCheck :size="21"/></header><dl class="definition-grid"><div><dt>Full name</dt><dd>{{ borrower.next_of_kin }}</dd></div><div><dt>Relationship</dt><dd>{{ borrower.next_of_kin_relationship }}</dd></div><div><dt>Phone</dt><dd>{{ borrower.next_of_kin_phone }}</dd></div><div><dt>Alternative phone</dt><dd>{{ borrower.next_of_kin_alternative_phone || '—' }}</dd></div><div class="sm:col-span-2"><dt>Address</dt><dd>{{ borrower.next_of_kin_address || '—' }}</dd></div></dl></section>
      <section v-else class="premium-panel overflow-hidden"><header class="panel-heading"><div><p class="eyebrow">Credit history</p><h2>Loans</h2></div></header><div v-if="!borrower.loans.length" class="empty-state"><h2>No loans yet</h2><p>This borrower is registered and ready for product eligibility checks.</p></div><div v-else class="overflow-x-auto"><table class="data-table"><thead><tr><th>Loan</th><th>Product</th><th>Principal</th><th>Total payable</th><th>Outstanding</th><th>Status</th></tr></thead><tbody><tr v-for="loan in borrower.loans" :key="loan.id"><td><RouterLink :to="`/loans/${loan.id}`">{{ loan.loan_number }}</RouterLink></td><td>{{ loan.product?.name || 'Legacy loan' }}</td><td>{{ money(loan.principal_amount) }}</td><td>{{ money(loan.total_payable) }}</td><td class="font-semibold">{{ money(loan.outstanding_amount) }}</td><td><StatusBadge :status="loan.status"/></td></tr></tbody></table></div></section>
    </template>
  </div>
</template>
