<script setup>
import { onMounted, ref, watch } from 'vue'
import { PhPhone as Phone, PhWallet as Wallet, PhX as X } from '@phosphor-icons/vue'
import StatusBadge from '../components/StatusBadge.vue'
import { borrowers, money } from '../data/demo'
import api from '../services/api'
const activeTab = ref('Due Today'); const collecting = ref(null); const amount = ref(''); const records = ref(borrowers.filter(b => b.status !== 'Completed')); const saving = ref(false); const message = ref('')
const tabs = ['Due Today', 'Overdue', 'Upcoming', 'Collected']
const views = { 'Due Today': 'due_today', Overdue: 'overdue', Upcoming: 'upcoming', Collected: 'collected' }
async function load() { try { const { data } = await api.get('/collections', { params: { view: views[activeTab.value] } }); records.value = data.data.map((item) => ({ id: item.id, loanId: item.loan_id, name: item.loan.borrower.full_name, phone: item.loan.borrower.phone_number, loan: item.loan.loan_number, outstanding: item.loan.outstanding_amount, due: item.amount_due - item.amount_paid, status: new Date(item.due_date) < new Date() ? 'Overdue' : 'Due Today' })) } catch { /* Keep demo queue. */ } }
async function confirmPayment() { if (!collecting.value.loanId) return; saving.value = true; try { await api.post(`/loans/${collecting.value.loanId}/repayments`, { amount: Number(amount.value), payment_method: 'cash' }); message.value = `Payment of ${money(amount.value)} received.`; collecting.value = null; await load() } finally { saving.value = false } }
onMounted(load); watch(activeTab, load)
</script>
<template><div><p v-if="message" class="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{{ message }}</p><div class="mb-5 flex gap-2 overflow-x-auto pb-1"><button v-for="tab in tabs" :key="tab" class="min-h-10 shrink-0 rounded-xl px-4 text-sm font-semibold" :class="activeTab === tab ? 'bg-stone-950 text-white' : 'bg-white text-stone-600 ring-1 ring-stone-200'" @click="activeTab = tab">{{ tab }}</button></div><section class="grid gap-3"><article v-for="person in records" :key="person.id" class="surface flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div class="flex-1"><div class="flex items-center gap-3"><h2 class="font-bold">{{ person.name }}</h2><StatusBadge :status="person.status"/></div><p class="mt-1 text-sm text-stone-500">{{ person.phone }} · {{ person.loan }}</p></div><div class="sm:text-right"><p class="text-xs text-stone-500">Amount due</p><p class="mt-1 text-lg font-bold">{{ money(person.due || Math.min(person.outstanding, 250000)) }}</p></div><div class="flex gap-2"><a :href="`tel:${person.phone}`" class="btn-secondary"><Phone :size="18"/>Call</a><button class="btn-primary" @click="collecting = person; amount = person.due || Math.min(person.outstanding, 250000)"><Wallet :size="18"/>Collect</button></div></article></section><div v-if="collecting" class="fixed inset-0 z-40 grid place-items-end bg-stone-950/40 sm:place-items-center" @click.self="collecting = null"><section class="w-full rounded-t-2xl bg-white p-6 sm:max-w-md sm:rounded-2xl"><div class="flex items-center justify-between"><div><h2 class="text-xl font-bold">Collect payment</h2><p class="mt-1 text-sm text-stone-500">{{ collecting.name }}</p></div><button class="grid size-10 place-items-center rounded-xl bg-stone-100" @click="collecting = null"><X :size="20"/></button></div><div class="mt-6 rounded-xl bg-stone-50 p-4"><p class="text-sm text-stone-500">Outstanding balance</p><p class="mt-1 text-2xl font-bold">{{ money(collecting.outstanding) }}</p></div><label class="mt-5 block"><span class="label">Amount received</span><input v-model="amount" type="number" class="field text-lg font-bold"/></label><label class="mt-4 block"><span class="label">Payment method</span><select class="field"><option>Cash</option><option>MTN Mobile Money</option><option>Airtel Money</option><option>Bank</option></select></label><button class="btn-primary mt-6 w-full" :disabled="saving" @click="confirmPayment">{{ saving ? 'Recording...' : 'Confirm payment' }}</button></section></div></div></template>
