<script setup>
import { nextTick, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { PhPhone, PhReceipt, PhWallet, PhX } from '@phosphor-icons/vue'
import StatusBadge from '../components/StatusBadge.vue'
import { date, money } from '../utils/formatters'
import api from '../services/api'

const route = useRoute(); const router = useRouter(); const activeTab = ref(route.query.view === 'overdue' ? 'Overdue' : route.query.view === 'upcoming' ? 'Upcoming' : 'Due today'); const collecting = ref(null); const amount = ref(''); const method = ref('cash'); const reference = ref(''); const records = ref([]); const loading = ref(true); const saving = ref(false); const error = ref(''); const receipt = ref(null)
const tabs = ['Due today', 'Overdue', 'Upcoming']; const views = { 'Due today': 'due_today', Overdue: 'overdue', Upcoming: 'upcoming' }
async function load() { loading.value = true; error.value = ''; try { const { data } = await api.get('/collections', { params: { view: views[activeTab.value] } }); records.value = data.data.map((item) => ({ id: item.id, loanId: item.loan_id, borrowerId: item.loan.borrower.id, name: item.loan.borrower.full_name, phone: item.loan.borrower.phone_number, loan: item.loan.loan_number, outstanding: item.loan.outstanding_amount, due: item.amount_due - item.amount_paid, dueDate: item.due_date, status: new Date(`${item.due_date}T23:59:59`) < new Date() ? 'Overdue' : 'Due Today' })); const requested = route.query.loan && records.value.find((item) => item.loanId === route.query.loan); if (requested) await nextTick(() => openCollection(requested)) } catch (e) { error.value = e.response?.data?.message || 'Collection queue could not be loaded.' } finally { loading.value = false } }
function openCollection(item) { collecting.value = item; amount.value = item.due; method.value = 'cash'; reference.value = ''; receipt.value = null }
async function close() { collecting.value = null; receipt.value = null; await router.replace({ path: '/collections' }); await load() }
async function confirmPayment() { saving.value = true; error.value = ''; try { const { data } = await api.post(`/loans/${collecting.value.loanId}/repayments`, { amount: Number(amount.value), payment_method: method.value, transaction_reference: reference.value || null }); receipt.value = data.receipt } catch (e) { error.value = Object.values(e.response?.data?.errors || {})[0]?.[0] || e.response?.data?.message || 'Repayment could not be recorded.' } finally { saving.value = false } }
onMounted(load); watch(activeTab, load)
</script>
<template><div class="space-y-4"><div class="flex gap-1 overflow-x-auto border-b border-[#dfe4e8]"><button v-for="tab in tabs" :key="tab" class="shrink-0 border-b-2 px-4 py-2.5 text-sm font-semibold" :class="activeTab === tab ? 'border-[#287f71] text-[#1f675c]' : 'border-transparent text-[#667085]'" @click="activeTab = tab">{{ tab }}</button></div><p v-if="error && !collecting" class="border-l-4 border-red-500 bg-red-50 p-3 text-sm text-red-800">{{ error }} <button class="ml-2 font-semibold underline" @click="load">Retry</button></p><div v-if="loading" class="surface p-8 text-center text-sm text-[#667085]">Loading collection queue</div><div v-else-if="!records.length" class="surface p-10 text-center text-sm text-[#667085]">No installments in this queue.</div><section v-else class="surface overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[780px] text-left text-sm"><thead class="bg-[#f8fafb] text-[.68rem] font-bold uppercase tracking-wide text-[#7d8796]"><tr><th class="px-5 py-3">Borrower</th><th class="px-4 py-3">Loan</th><th class="px-4 py-3">Due date</th><th class="px-4 py-3">Amount due</th><th class="px-4 py-3">Status</th><th class="px-5 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-[#edf0f2]"><tr v-for="item in records" :key="item.id" class="hover:bg-[#fafcfc]"><td class="px-5 py-3.5"><RouterLink :to="`/borrowers/${item.borrowerId}`" class="font-semibold text-[#1d2939]">{{ item.name }}</RouterLink><p class="mt-1 text-xs text-[#7d8796]">{{ item.phone }}</p></td><td class="px-4 py-3.5"><RouterLink :to="`/loans/${item.loanId}`" class="font-medium text-[#287f71]">{{ item.loan }}</RouterLink></td><td class="px-4 py-3.5">{{ date(item.dueDate) }}</td><td class="px-4 py-3.5 font-semibold tabular-nums">{{ money(item.due) }}</td><td class="px-4 py-3.5"><StatusBadge :status="item.status"/></td><td class="px-5 py-3.5"><div class="flex justify-end gap-2"><a :href="`tel:${item.phone}`" class="btn-secondary !min-h-8 !px-2.5 !text-xs"><PhPhone :size="15"/>Call</a><button class="btn-primary !min-h-8 !px-2.5 !text-xs" @click="openCollection(item)"><PhWallet :size="15"/>Collect</button></div></td></tr></tbody></table></div></section>
  <div v-if="collecting" class="fixed inset-0 z-50 grid place-items-end bg-slate-950/40 sm:place-items-center" @click.self="close"><section class="w-full rounded-t-[10px] bg-white shadow-2xl sm:max-w-md sm:rounded-[10px]"><header class="flex items-center justify-between border-b border-[#e8ecef] px-5 py-4"><div><h2 class="font-semibold text-[#1d2939]">{{ receipt ? 'Payment receipt' : 'Record repayment' }}</h2><p class="mt-1 text-xs text-[#667085]">{{ collecting.name }} · {{ collecting.loan }}</p></div><button class="icon-button" aria-label="Close" @click="close"><PhX :size="18"/></button></header><div v-if="receipt" class="p-6"><div class="border border-dashed border-[#bfc8d0] p-5 text-center"><PhReceipt :size="30" class="mx-auto text-[#287f71]"/><p class="mt-3 text-xs font-bold uppercase tracking-wide text-[#7d8796]">{{ receipt.receipt_number }}</p><p class="mt-3 text-3xl font-semibold tabular-nums text-[#1d2939]">{{ money(receipt.amount_paid) }}</p><dl class="mt-5 divide-y divide-[#edf0f2] text-sm"><div class="flex justify-between py-3"><dt class="text-[#667085]">Remaining balance</dt><dd class="font-semibold">{{ money(receipt.remaining_balance) }}</dd></div><div class="flex justify-between py-3"><dt class="text-[#667085]">Payment method</dt><dd class="capitalize">{{ method.replace('_', ' ') }}</dd></div></dl></div><div class="mt-5 flex gap-2"><button class="btn-secondary flex-1" @click="window.print()">Print</button><button class="btn-primary flex-1" @click="close">Done</button></div></div><form v-else class="p-5" @submit.prevent="confirmPayment"><p v-if="error" class="mb-4 border-l-4 border-red-500 bg-red-50 p-3 text-sm text-red-800">{{ error }}</p><dl class="mb-5 grid grid-cols-2 gap-px overflow-hidden rounded-[7px] bg-[#dfe4e8]"><div class="bg-[#f8fafb] p-3"><dt class="text-xs text-[#667085]">Due now</dt><dd class="mt-1 font-semibold">{{ money(collecting.due) }}</dd></div><div class="bg-[#f8fafb] p-3"><dt class="text-xs text-[#667085]">Loan balance</dt><dd class="mt-1 font-semibold">{{ money(collecting.outstanding) }}</dd></div></dl><div class="space-y-4"><label><span class="label">Amount received</span><input v-model="amount" type="number" min="1" :max="collecting.outstanding" class="field text-base font-semibold" required/></label><label><span class="label">Payment method</span><select v-model="method" class="field"><option value="cash">Cash</option><option value="mtn_momo">MTN Mobile Money</option><option value="airtel_money">Airtel Money</option><option value="bank">Bank transfer</option></select></label><label v-if="method !== 'cash'"><span class="label">Transaction reference</span><input v-model.trim="reference" class="field" required/></label></div><button class="btn-primary mt-6 w-full" :disabled="saving">{{ saving ? 'Posting repayment' : 'Confirm repayment' }}</button></form></section></div>
</div></template>
