<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { PhArrowLeft, PhArrowRight, PhCheck, PhUserPlus } from '@phosphor-icons/vue'
import { money } from '../utils/formatters'
import api from '../services/api'

const router = useRouter(); const route = useRoute(); const step = ref(1); const borrowers = ref([]); const branches = ref([]); const loading = ref(true); const saving = ref(false); const error = ref('')
const iso = (date) => date.toISOString().slice(0, 10); const today = new Date(); const first = new Date(); first.setDate(first.getDate() + 7)
const form = reactive({ borrower_id: '', branch_id: '', principal_amount: 500000, interest_rate: 10, duration: 4, duration_unit: 'weeks', repayment_frequency: 'weekly', disbursement_date: iso(today), first_repayment_date: iso(first), fees_amount: 0, interest_method: 'simple', interest_period: 'loan_term' })
const interest = computed(() => Math.round(Number(form.principal_amount) * Number(form.interest_rate) / 100)); const total = computed(() => Number(form.principal_amount) + interest.value + Number(form.fees_amount)); const installment = computed(() => Math.ceil(total.value / Math.max(1, Number(form.duration)))); const selected = computed(() => borrowers.value.find((item) => item.id === form.borrower_id))
async function load() { try { const [borrowerResponse, branchResponse] = await Promise.all([api.get('/borrowers'), api.get('/branches')]); borrowers.value = borrowerResponse.data.data; branches.value = branchResponse.data; form.borrower_id = borrowers.value.find((item) => item.id === route.query.borrower)?.id || borrowers.value[0]?.id || ''; form.branch_id = selected.value?.branch_id || branches.value[0]?.id || '' } catch (e) { error.value = e.response?.data?.message || 'Loan form data could not be loaded.' } finally { loading.value = false } }
function next() { if (step.value === 1 && !form.borrower_id) { error.value = 'Select a borrower before continuing.'; return } error.value = ''; step.value++ }
async function createLoan() { saving.value = true; error.value = ''; try { const { data } = await api.post('/loans', form); router.push(`/loans/${data.id}`) } catch (e) { error.value = Object.values(e.response?.data?.errors || {})[0]?.[0] || e.response?.data?.message || 'Loan could not be created.' } finally { saving.value = false } }
onMounted(load)
</script>
<template><div class="mx-auto max-w-4xl"><div class="mb-5 grid grid-cols-3 overflow-hidden rounded-[8px] border border-[#dfe4e8] bg-white" aria-label="Loan steps"><div v-for="n in 3" :key="n" class="flex items-center gap-2 border-r border-[#e8ecef] px-3 py-3 text-sm last:border-r-0" :class="n === step ? 'bg-[#eaf4f2] font-semibold text-[#1f675c]' : n < step ? 'text-[#287f71]' : 'text-[#8a94a3]' "><span class="grid size-6 place-items-center rounded-[5px] border text-xs" :class="n <= step ? 'border-[#287f71] bg-[#287f71] text-white' : 'border-[#cfd6dc]'">{{ n < step ? '✓' : n }}</span><span>{{ ['Borrower','Terms','Review'][n-1] }}</span></div></div>
  <section class="surface overflow-hidden"><header class="border-b border-[#e8ecef] px-5 py-4"><h2 class="font-semibold text-[#1d2939]">{{ ['Select borrower','Loan terms','Confirm loan'][step-1] }}</h2></header><div class="p-5 sm:p-7"><p v-if="error" class="mb-5 border-l-4 border-red-500 bg-red-50 p-3 text-sm text-red-800">{{ error }}</p><div v-if="loading" class="py-8 text-center text-sm text-[#667085]">Loading loan form</div>
    <div v-else-if="step === 1"><label class="label" for="borrower">Borrower</label><select id="borrower" v-model="form.borrower_id" class="field" @change="form.branch_id = selected?.branch_id || form.branch_id"><option value="" disabled>Select borrower</option><option v-for="person in borrowers" :key="person.id" :value="person.id">{{ person.full_name }} · {{ person.phone_number }}</option></select><RouterLink to="/borrowers?add=1" class="btn-secondary mt-4"><PhUserPlus :size="17"/>Add borrower</RouterLink><p v-if="!borrowers.length" class="mt-4 text-sm text-amber-700">Add a borrower before issuing a loan.</p></div>
    <div v-else-if="step === 2" class="grid gap-5 sm:grid-cols-2"><label><span class="label">Principal amount (UGX)</span><input v-model.number="form.principal_amount" type="number" min="1000" class="field" required/></label><label><span class="label">Interest rate (%)</span><input v-model.number="form.interest_rate" type="number" min="0" max="100" step="0.1" class="field"/></label><label><span class="label">Duration</span><input v-model.number="form.duration" type="number" min="1" max="60" class="field"/></label><label><span class="label">Duration unit</span><select v-model="form.duration_unit" class="field"><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option></select></label><label><span class="label">Repayment frequency</span><select v-model="form.repayment_frequency" class="field"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="biweekly">Every two weeks</option><option value="monthly">Monthly</option></select></label><label><span class="label">Processing fees (UGX)</span><input v-model.number="form.fees_amount" type="number" min="0" class="field"/></label><label><span class="label">Disbursement date</span><input v-model="form.disbursement_date" type="date" class="field"/></label><label><span class="label">First repayment date</span><input v-model="form.first_repayment_date" type="date" :min="form.disbursement_date" class="field"/></label><dl class="grid gap-px overflow-hidden rounded-[7px] border border-[#d9e8e5] bg-[#d9e8e5] sm:col-span-2 sm:grid-cols-3"><div v-for="row in [['Principal', money(form.principal_amount)],['Total payable', money(total)],['Installment', money(installment)]]" :key="row[0]" class="bg-[#f3f9f8] p-4"><dt class="text-xs text-[#56736e]">{{ row[0] }}</dt><dd class="mt-1 font-semibold tabular-nums text-[#173f3a]">{{ row[1] }}</dd></div></dl></div>
    <dl v-else class="divide-y divide-[#e8ecef] rounded-[7px] border border-[#e1e6ea] px-5"><div v-for="row in [['Borrower', selected?.full_name],['Principal', money(form.principal_amount)],['Interest', money(interest)],['Fees', money(form.fees_amount)],['Total payable', money(total)],['Repayment', `${form.duration} ${form.repayment_frequency} installments`],['First payment', form.first_repayment_date]]" :key="row[0]" class="flex justify-between gap-5 py-3.5 text-sm"><dt class="text-[#667085]">{{ row[0] }}</dt><dd class="text-right font-semibold text-[#1d2939]">{{ row[1] }}</dd></div></dl>
  </div><footer v-if="!loading" class="flex justify-between border-t border-[#e8ecef] bg-[#fafbfc] px-5 py-4"><button v-if="step > 1" class="btn-secondary" @click="step--"><PhArrowLeft :size="17"/>Back</button><span v-else/><button v-if="step < 3" class="btn-primary" :disabled="!borrowers.length" @click="next">Continue<PhArrowRight :size="17"/></button><button v-else class="btn-primary" :disabled="saving" @click="createLoan"><PhCheck :size="17"/>{{ saving ? 'Creating loan' : 'Confirm loan' }}</button></footer></section>
</div></template>
