<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { PhArrowLeft, PhPrinter, PhReceipt, PhShieldCheck, PhWallet } from '@phosphor-icons/vue'
import StatusBadge from '../components/StatusBadge.vue'
import { date, dateTime, money } from '../utils/formatters'
import api from '../services/api'

const route = useRoute()
const loan = ref(null)
const loading = ref(true)
const error = ref('')
const paid = computed(() => loan.value ? Number(loan.value.total_payable) - Number(loan.value.outstanding_amount) : 0)
async function load() { loading.value = true; error.value = ''; try { loan.value = (await api.get(`/loans/${route.params.id}`)).data } catch (e) { error.value = e.response?.status === 404 ? 'Loan account not found.' : 'Loan account could not be loaded.' } finally { loading.value = false } }
onMounted(load)
</script>
<template><div class="space-y-5"><RouterLink to="/loans" class="inline-flex items-center gap-2 text-sm font-semibold text-[#667085]"><PhArrowLeft :size="17"/>Loans</RouterLink>
  <div v-if="loading" class="surface p-8 text-center text-sm text-[#667085]">Loading loan account</div><p v-else-if="error" class="border-l-4 border-red-500 bg-red-50 p-3 text-sm text-red-800">{{ error }} <button class="ml-2 font-semibold underline" @click="load">Retry</button></p>
  <template v-else><section class="surface agreement-sheet overflow-hidden"><header class="flex flex-col gap-4 border-b border-[#e8ecef] p-5 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex items-center gap-3"><h2 class="text-lg font-semibold text-[#1d2939]">{{ loan.loan_number }}</h2><StatusBadge :status="loan.status === 'completed' ? 'Completed' : 'Active'"/></div><RouterLink :to="`/borrowers/${loan.borrower.id}`" class="mt-1.5 block text-sm font-medium text-[#287f71]">{{ loan.borrower.full_name }} · {{ loan.borrower.phone_number }}</RouterLink></div><div class="no-print flex flex-wrap gap-2"><button class="btn-secondary" @click="window.print()"><PhPrinter :size="17"/>Print agreement</button><RouterLink v-if="loan.status === 'active'" :to="{ path: '/collections', query: { loan: loan.id } }" class="btn-primary"><PhWallet :size="17"/>Record repayment</RouterLink></div></header><dl class="grid gap-px bg-[#e8ecef] sm:grid-cols-2 xl:grid-cols-5"><div v-for="row in [['Principal', money(loan.principal_amount)],['Interest', money(loan.total_interest)],['Total payable', money(loan.total_payable)],['Paid', money(paid)],['Outstanding', money(loan.outstanding_amount)]]" :key="row[0]" class="bg-white px-5 py-4"><dt class="text-[.68rem] font-bold uppercase tracking-wide text-[#8a94a3]">{{ row[0] }}</dt><dd class="mt-1.5 font-semibold tabular-nums text-[#1d2939]">{{ row[1] }}</dd></div></dl><div class="loan-terms-strip"><PhShieldCheck :size="21"/><div><strong>{{ loan.product?.name || 'Legacy loan terms' }}</strong><span>{{ Number(loan.interest_rate).toFixed(2) }}% {{ loan.interest_period?.replace('_', ' ') }} · {{ loan.interest_method }} interest · {{ loan.duration }} {{ loan.duration_unit }} · {{ loan.repayment_frequency }}</span></div><div><small>Purpose</small><p>{{ loan.purpose || 'Not captured on this legacy loan' }}</p></div></div></section>
    <div class="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section class="surface overflow-hidden"><header class="border-b border-[#e8ecef] px-5 py-4"><h2 class="font-semibold text-[#1d2939]">Repayment schedule</h2></header><div class="overflow-x-auto"><table class="w-full min-w-[580px] text-left text-sm"><thead class="bg-[#f8fafb] text-[.68rem] font-bold uppercase tracking-wide text-[#7d8796]"><tr><th class="px-5 py-3">No.</th><th class="px-4 py-3">Due date</th><th class="px-4 py-3">Amount due</th><th class="px-4 py-3">Paid</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-[#edf0f2]"><tr v-for="item in loan.schedules" :key="item.id"><td class="px-5 py-3">{{ item.installment_number }}</td><td class="px-4 py-3">{{ date(item.due_date) }}</td><td class="px-4 py-3 tabular-nums">{{ money(item.amount_due) }}</td><td class="px-4 py-3 tabular-nums">{{ money(item.amount_paid) }}</td><td class="px-5 py-3"><span class="capitalize">{{ item.status.replace('_', ' ') }}</span></td></tr></tbody></table></div></section>
      <section class="surface overflow-hidden"><header class="flex items-center justify-between border-b border-[#e8ecef] px-5 py-4"><h2 class="font-semibold text-[#1d2939]">Repayments & receipts</h2><PhReceipt :size="19" class="text-[#287f71]"/></header><div v-if="!loan.repayments.length" class="p-8 text-center text-sm text-[#667085]">No repayments recorded.</div><div v-else class="divide-y divide-[#edf0f2]"><article v-for="payment in loan.repayments" :key="payment.id" class="flex items-start justify-between gap-3 px-5 py-4"><div><p class="font-semibold tabular-nums" :class="payment.entry_type === 'reversal' ? 'text-red-700' : 'text-[#1d2939]'">{{ money(payment.amount) }}</p><p class="mt-1 text-xs capitalize text-[#7d8796]">{{ payment.payment_method.replace('_', ' ') }} · {{ payment.entry_type }}</p><RouterLink v-if="payment.receipt" :to="`/receipts/${payment.receipt.id}`" class="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-[#287f71]"><PhReceipt :size="14"/>{{ payment.receipt.status === 'reversed' ? 'View reversed receipt' : 'View receipt' }}</RouterLink></div><time class="text-xs text-[#7d8796]">{{ dateTime(payment.paid_at) }}</time></article></div></section></div>
  </template></div></template>
