<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import api from '../services/api'
const router = useRouter(); const loading = ref(false); const error = ref('')
const form = reactive({ tenant: 'kiboga-capital', email: 'owner@kiboga.ug', password: 'password' })
async function submit() { loading.value = true; error.value = ''; try { const { data } = await api.post('/auth/login', form); localStorage.setItem('kopa_token', data.token); localStorage.setItem('kopa_tenant', data.tenant.slug); router.push('/') } catch (e) { error.value = e.response?.data?.message || 'Could not sign in. Check the API connection.' } finally { loading.value = false } }
</script>
<template><main class="grid min-h-[100dvh] bg-[#143b31] lg:grid-cols-2"><section class="hidden p-12 text-white lg:flex lg:flex-col lg:justify-between"><div class="grid size-12 place-items-center rounded-xl bg-[#d9f75f] text-xl font-black text-[#143b31]">K</div><div><h1 class="max-w-lg text-5xl font-bold leading-tight tracking-tight">Know where every shilling goes.</h1><p class="mt-5 max-w-md text-lg text-emerald-50/70">Simple loan tracking for growing lending teams.</p></div><p class="text-sm text-emerald-50/50">Kopa Loan Management</p></section><section class="grid place-items-center bg-[#f4f7f5] p-5 sm:p-10"><form class="w-full max-w-md surface p-6 sm:p-8" @submit.prevent="submit"><div class="mb-7 lg:hidden"><div class="grid size-11 place-items-center rounded-xl bg-emerald-800 font-black text-white">K</div></div><h2 class="text-2xl font-bold">Welcome back</h2><p class="mt-2 text-sm text-stone-500">Sign in to your lending company.</p><p v-if="error" class="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{{ error }}</p><div class="mt-6 space-y-4"><label><span class="label">Company code</span><input v-model="form.tenant" class="field" required/></label><label><span class="label">Email</span><input v-model="form.email" type="email" class="field" required/></label><label><span class="label">Password</span><input v-model="form.password" type="password" class="field" required/></label></div><button class="btn-primary mt-6 w-full" :disabled="loading">{{ loading ? 'Signing in...' : 'Sign in' }}</button><p class="mt-5 text-center text-sm text-stone-500">New lender? <RouterLink to="/register" class="font-semibold text-emerald-800">Create company</RouterLink></p></form></section></main></template>
