<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import api from '../services/api'
const router = useRouter(); const loading = ref(false); const error = ref('')
const form = reactive({ company_name: '', company_phone: '', name: '', email: '', phone: '', password: '', password_confirmation: '' })
async function submit() { loading.value = true; error.value = ''; try { const { data } = await api.post('/auth/register-company', form); localStorage.setItem('kopa_token', data.token); localStorage.setItem('kopa_tenant', data.tenant.slug); router.push('/') } catch (e) { error.value = e.response?.data?.message || 'Company setup failed. Please try again.' } finally { loading.value = false } }
</script>
<template><main class="grid min-h-[100dvh] place-items-center bg-[#f4f7f5] p-5 sm:p-10"><form class="w-full max-w-2xl surface p-6 sm:p-8" @submit.prevent="submit"><div class="flex items-center gap-3"><div class="grid size-11 place-items-center rounded-xl bg-emerald-800 font-black text-white">K</div><div><h1 class="text-2xl font-bold">Create your lending company</h1><p class="text-sm text-stone-500">Your secure workspace will be prepared automatically.</p></div></div><p v-if="error" class="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{{ error }}</p><div class="mt-7 grid gap-5 sm:grid-cols-2"><label><span class="label">Company name</span><input v-model="form.company_name" class="field" required/></label><label><span class="label">Company phone</span><input v-model="form.company_phone" class="field"/></label><label><span class="label">Your name</span><input v-model="form.name" class="field" required/></label><label><span class="label">Your phone</span><input v-model="form.phone" class="field"/></label><label class="sm:col-span-2"><span class="label">Email</span><input v-model="form.email" type="email" class="field" required/></label><label><span class="label">Password</span><input v-model="form.password" type="password" class="field" minlength="8" required/></label><label><span class="label">Confirm password</span><input v-model="form.password_confirmation" type="password" class="field" required/></label></div><button class="btn-primary mt-7 w-full" :disabled="loading">{{ loading ? 'Preparing company...' : 'Create company' }}</button><p class="mt-5 text-center text-sm text-stone-500">Already registered? <RouterLink to="/login" class="font-semibold text-emerald-800">Sign in</RouterLink></p></form></main></template>
