<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { PhDownloadSimple } from '@phosphor-icons/vue'
import { money } from '../utils/formatters'
import api from '../services/api'

const month = ref(new Date().toISOString().slice(0, 7)); const report = ref(null); const loading = ref(true); const error = ref('')
const range = computed(() => { const [year, value] = month.value.split('-').map(Number); const lastDay = String(new Date(year, value, 0).getDate()).padStart(2, '0'); return { from: `${month.value}-01`, to: `${month.value}-${lastDay}` } })
const stats = computed(() => report.value ? [['Money lent', report.value.money_lent],['Money collected', report.value.money_collected],['Interest expected', report.value.interest_expected],['Outstanding', report.value.outstanding],['Overdue', report.value.overdue]] : [])
async function load() { loading.value = true; error.value = ''; try { report.value = (await api.get('/reports/summary', { params: range.value })).data } catch (e) { error.value = e.response?.data?.message || 'Report data could not be loaded.' } finally { loading.value = false } }
function exportCsv() { if (!report.value) return; const rows = [['Metric','Amount'], ...stats.value, [], ['Staff member','Payments','Amount'], ...report.value.collections_by_staff.map((row) => [row.name,row.payments,row.amount])]; const blob = new Blob([rows.map((row) => row.join(',')).join('\n')], { type: 'text/csv' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `kopa-report-${month.value}.csv`; link.click(); URL.revokeObjectURL(link.href) }
onMounted(load); watch(month, load)
</script>
<template><div class="space-y-5"><section class="surface overflow-hidden"><header class="flex flex-col gap-3 border-b border-[#e8ecef] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold text-[#1d2939]">Monthly summary</h2><p class="mt-1 text-xs text-[#7d8796]">All branches</p></div><div class="flex gap-2"><input v-model="month" type="month" class="field !w-auto"/><button class="btn-secondary" :disabled="!report" @click="exportCsv"><PhDownloadSimple :size="17"/>Export CSV</button></div></header><p v-if="error" class="m-5 border-l-4 border-red-500 bg-red-50 p-3 text-sm text-red-800">{{ error }} <button class="ml-2 font-semibold underline" @click="load">Retry</button></p><div v-if="loading" class="p-8 text-center text-sm text-[#667085]">Loading report</div><dl v-else class="grid gap-px bg-[#e8ecef] sm:grid-cols-2 xl:grid-cols-5"><div v-for="item in stats" :key="item[0]" class="bg-white p-5"><dt class="text-[.7rem] font-bold uppercase tracking-wide text-[#7d8796]">{{ item[0] }}</dt><dd class="mt-2 text-xl font-semibold tabular-nums text-[#1d2939]">{{ money(item[1]) }}</dd></div></dl></section><section class="surface overflow-hidden"><header class="border-b border-[#e8ecef] px-5 py-4"><h2 class="font-semibold text-[#1d2939]">Collections by staff</h2></header><div v-if="report && !report.collections_by_staff.length" class="p-8 text-center text-sm text-[#667085]">No repayments were posted in this period.</div><div v-else class="divide-y divide-[#edf0f2]"><div v-for="row in report?.collections_by_staff" :key="row.id" class="grid grid-cols-[1fr_auto] gap-4 px-5 py-4"><div><p class="font-semibold text-[#1d2939]">{{ row.name }}</p><p class="mt-1 text-xs text-[#7d8796]">{{ row.payments }} payment{{ row.payments === 1 ? '' : 's' }}</p></div><strong class="tabular-nums">{{ money(row.amount) }}</strong></div></div></section></div></template>
