<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useAuthStore } from '../stores/auth'
import api from '../services/api'
const auth = useAuthStore(); const loading = ref(true); const saving = ref(false); const error = ref(''); const message = ref(''); const form = reactive({ name: '', phone: '', email: '', address: '', currency: 'UGX' })
async function load() { loading.value = true; error.value = ''; try { const { data } = await api.get('/company'); Object.assign(form, { name: data.name, phone: data.settings?.phone || '', email: data.settings?.email || '', address: data.settings?.address || '', currency: data.settings?.currency || 'UGX' }) } catch (e) { error.value = e.response?.data?.message || 'Company settings could not be loaded.' } finally { loading.value = false } }
async function save() { saving.value = true; error.value = ''; message.value = ''; try { const { data } = await api.put('/company', form); auth.tenant.name = data.name; localStorage.setItem('kopa_company', JSON.stringify(auth.tenant)); message.value = 'Company settings saved.' } catch (e) { error.value = Object.values(e.response?.data?.errors || {})[0]?.[0] || e.response?.data?.message || 'Settings could not be saved.' } finally { saving.value = false } }
onMounted(load)
</script>
<template><section class="surface mx-auto max-w-4xl overflow-hidden"><header class="border-b border-[#e8ecef] px-5 py-4"><h2 class="font-semibold text-[#1d2939]">Company details</h2><p class="mt-1 text-xs text-[#7d8796]">Used on account records and receipts</p></header><div v-if="loading" class="p-8 text-center text-sm text-[#667085]">Loading settings</div><form v-else class="p-5 sm:p-7" @submit.prevent="save"><p v-if="error" class="mb-5 border-l-4 border-red-500 bg-red-50 p-3 text-sm text-red-800">{{ error }}</p><p v-if="message" class="mb-5 border-l-4 border-[#287f71] bg-[#eef7f5] p-3 text-sm text-[#1f675c]">{{ message }}</p><div class="grid gap-5 sm:grid-cols-2"><label><span class="label">Company name</span><input v-model.trim="form.name" class="field" required/></label><label><span class="label">Phone</span><input v-model.trim="form.phone" class="field"/></label><label><span class="label">Email</span><input v-model.trim="form.email" type="email" class="field"/></label><label><span class="label">Currency</span><select v-model="form.currency" class="field"><option value="UGX">UGX — Uganda Shilling</option></select></label><label class="sm:col-span-2"><span class="label">Address</span><input v-model.trim="form.address" class="field"/></label></div><div class="mt-7 flex justify-end"><button class="btn-primary" :disabled="saving">{{ saving ? 'Saving' : 'Save changes' }}</button></div></form></section></template>
