<script setup>
import { onMounted, reactive, ref } from 'vue'
import { PhCheck, PhPencilSimple, PhPlus, PhPower } from '@phosphor-icons/vue'
import { money } from '../utils/formatters'
import api from '../services/api'

const products = ref([]); const loading = ref(true); const saving = ref(false); const editingId = ref(null); const open = ref(false); const error = ref('')
const documentOptions = [['identity_document','Identification document'],['borrower_photo','Borrower photo'],['proof_of_residence','Proof of residence'],['lc1_letter','LC1 letter'],['income_evidence','Income evidence'],['business_evidence','Business evidence'],['bank_statement','Bank statement'],['mobile_money_statement','Mobile money statement']]
const empty = () => ({ name: '', description: '', is_active: true, principal_amount: 100000, interest_rate: 2.8, interest_period: 'monthly', interest_method: 'simple', duration: 1, duration_unit: 'months', repayment_frequencies: ['weekly', 'monthly'], processing_fee_type: 'fixed', processing_fee_value: null, minimum_guarantors: 1, collateral_required: false, minimum_collateral_value_percent: null, required_documents: ['identity_document', 'borrower_photo'] })
const form = reactive(empty())
async function load() { loading.value = true; try { products.value = (await api.get('/loan-products')).data.data } catch (e) { error.value = e.response?.data?.message || 'Loan products could not be loaded.' } finally { loading.value = false } }
function create() { editingId.value = null; Object.assign(form, empty()); open.value = true }
function edit(product) { editingId.value = product.id; Object.assign(form, JSON.parse(JSON.stringify(product))); open.value = true }
function toggle(array, value) { const index = array.indexOf(value); index >= 0 ? array.splice(index, 1) : array.push(value) }
async function save() { saving.value = true; error.value = ''; try { editingId.value ? await api.put(`/loan-products/${editingId.value}`, form) : await api.post('/loan-products', form); open.value = false; await load() } catch (e) { error.value = Object.values(e.response?.data?.errors || {})[0]?.[0] || e.response?.data?.message || 'Loan product could not be saved.' } finally { saving.value = false } }
async function disable(product) { try { await api.patch(`/loan-products/${product.id}/disable`); await load() } catch (e) { error.value = e.response?.data?.message || 'Loan product could not be disabled.' } }
onMounted(load)
</script>

<template>
  <section class="premium-panel overflow-hidden"><header class="panel-heading"><div><p class="eyebrow">Pricing catalogue</p><h2>Loan products</h2><p>Rates are locked when staff issue a loan. Existing loans keep their original terms.</p></div><button class="btn-primary" @click="create"><PhPlus :size="17"/>New product</button></header>
    <p v-if="error" class="form-error m-5">{{ error }}</p><div v-if="loading" class="skeleton-stack m-6"><i/><i/></div>
    <div v-else-if="!products.length" class="empty-state"><h2>No loan products configured</h2><p>Create a product before issuing a new loan.</p><button class="btn-primary mt-5" @click="create"><PhPlus :size="17"/>Create product</button></div>
    <div v-else class="overflow-x-auto"><table class="data-table"><thead><tr><th>Product</th><th>Principal</th><th>Rate</th><th>Term</th><th>Requirements</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="product in products" :key="product.id"><td><strong>{{ product.name }}</strong><small>{{ product.code }}</small></td><td><strong>{{ money(product.principal_amount) }}</strong><small v-if="product.processing_fee_value">{{ product.processing_fee_type === 'percentage' ? `${Number(product.processing_fee_value)}%` : money(product.processing_fee_value) }} fee</small><small v-else>No processing fee</small></td><td><strong>{{ Number(product.interest_rate).toFixed(2) }}%</strong><small>per {{ product.interest_period.replace('_', ' ') }} · simple</small></td><td>{{ product.duration }} {{ product.duration_unit }}</td><td>{{ product.minimum_guarantors }} guarantor(s)<small>{{ product.collateral_required ? `${product.minimum_collateral_value_percent || 0}% collateral` : 'Collateral optional' }}</small></td><td><span :class="['status-chip', product.is_active ? 'positive' : 'neutral']">{{ product.is_active ? 'Active' : 'Disabled' }}</span></td><td><div class="row-actions"><button aria-label="Edit product" @click="edit(product)"><PhPencilSimple :size="17"/></button><button v-if="product.is_active" aria-label="Disable product" @click="disable(product)"><PhPower :size="17"/></button></div></td></tr></tbody></table></div>
  </section>
  <div v-if="open" class="modal-layer" @click.self="open = false"><section class="drawer-panel"><header class="panel-heading"><div><p class="eyebrow">Locked pricing</p><h2>{{ editingId ? 'Edit' : 'Create' }} loan product</h2></div><button class="text-button" @click="open = false">Close</button></header><form class="p-5 sm:p-7" @submit.prevent="save"><div class="form-grid"><label><span class="label">Product name</span><input v-model.trim="form.name" class="field" required/></label><label><span class="label">Principal amount (UGX)</span><input v-model.number="form.principal_amount" type="number" min="1000" step="1000" class="field" required/></label><label><span class="label">Interest rate (%)</span><input v-model.number="form.interest_rate" type="number" min="0" step="0.01" class="field" required/></label><label><span class="label">Rate basis</span><select v-model="form.interest_period" class="field"><option value="monthly">Per month</option><option value="annual">Per year</option><option value="loan_term">Full loan term</option></select></label><label><span class="label">Duration</span><input v-model.number="form.duration" type="number" min="1" class="field" required/></label><label><span class="label">Duration unit</span><select v-model="form.duration_unit" class="field"><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option></select></label><label><span class="label">Processing fee type</span><select v-model="form.processing_fee_type" class="field"><option value="fixed">Fixed amount</option><option value="percentage">Percentage</option></select></label><label><span class="label">{{ form.processing_fee_type === 'percentage' ? 'Processing fee (%)' : 'Processing fee (UGX)' }}</span><input v-model.number="form.processing_fee_value" type="number" min="0" :max="form.processing_fee_type === 'percentage' ? 99.99 : form.principal_amount - 1" :step="form.processing_fee_type === 'percentage' ? 0.01 : 1000" class="field" placeholder="No processing fee"/></label><label><span class="label">Minimum guarantors</span><input v-model.number="form.minimum_guarantors" type="number" min="0" max="5" class="field"/></label></div>
      <fieldset class="option-fieldset"><legend>Repayment frequencies</legend><label v-for="value in ['daily','weekly','biweekly','monthly']" :key="value"><input type="checkbox" :checked="form.repayment_frequencies.includes(value)" @change="toggle(form.repayment_frequencies, value)"/>{{ value === 'biweekly' ? 'Every two weeks' : value }}</label></fieldset>
      <div class="form-grid mt-5"><label class="consent-box wide"><input v-model="form.collateral_required" type="checkbox"/><span><strong>Collateral required</strong><small>Block issuance until security details are captured.</small></span></label><label v-if="form.collateral_required"><span class="label">Minimum collateral value (%)</span><input v-model.number="form.minimum_collateral_value_percent" type="number" min="0" class="field"/></label></div>
      <fieldset class="option-fieldset"><legend>Required borrower documents</legend><label v-for="item in documentOptions" :key="item[0]"><input type="checkbox" :checked="form.required_documents.includes(item[0])" @change="toggle(form.required_documents, item[0])"/>{{ item[1] }}</label></fieldset>
      <label class="mt-5 block"><span class="label">Description</span><textarea v-model.trim="form.description" class="field min-h-20 py-3"/></label><footer class="form-actions"><span class="flex-1"/><button class="btn-primary" :disabled="saving">{{ saving ? 'Saving product' : 'Save product' }}<PhCheck :size="17"/></button></footer></form></section></div>
</template>
